In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# manual - 1 Automatic - 0
# dealer - 1 Individual - 0
# Petrol - 1 Diesel - 2 CNG - 0

In [17]:
df = pd.read_csv('C:/Users/Kaustubh Sawant/OneDrive/Desktop/machine learning/car data.csv')
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,1,1,1,0
1,sx4,2013,4.75,9.54,43000,2,1,1,0
2,ciaz,2017,7.25,9.85,6900,1,1,1,0
3,wagon r,2011,2.85,4.15,5200,1,1,1,0
4,swift,2014,4.60,6.87,42450,2,1,1,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,2,1,1,0
297,brio,2015,4.00,5.90,60000,1,1,1,0
298,city,2009,3.35,11.00,87934,1,1,1,0
299,city,2017,11.50,12.50,9000,2,1,1,0
300,brio,2016,5.30,5.90,5464,1,1,1,0

In [18]:
#actual age of car
df['Car_Age'] = 2025 - df['Year']
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age
0,ritz,2014,3.35,5.59,27000,1,1,1,0,11
1,sx4,2013,4.75,9.54,43000,2,1,1,0,12
2,ciaz,2017,7.25,9.85,6900,1,1,1,0,8
3,wagon r,2011,2.85,4.15,5200,1,1,1,0,14
4,swift,2014,4.60,6.87,42450,2,1,1,0,11
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,2,1,1,0,9
297,brio,2015,4.00,5.90,60000,1,1,1,0,10
298,city,2009,3.35,11.00,87934,1,1,1,0,16
299,city,2017,11.50,12.50,9000,2,1,1,0,8
300,brio,2016,5.30,5.90,5464,1,1,1,0,9

In [19]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age
0,ritz,2014,3.35,5.59,27000,1,1,1,0,11
1,sx4,2013,4.75,9.54,43000,2,1,1,0,12
2,ciaz,2017,7.25,9.85,6900,1,1,1,0,8
3,wagon r,2011,2.85,4.15,5200,1,1,1,0,14
4,swift,2014,4.60,6.87,42450,2,1,1,0,11

In [20]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
Car_Age          0
dtype: int64

In [21]:
df.describe()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age
count,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000
mean,2013.627907,4.661296,7.628472,36947.205980,1.192691,0.647841,0.867110,0.043189,11.372093
std,2.891554,5.082812,8.644115,38886.883882,0.411598,0.478439,0.340021,0.247915,2.891554
min,2003.000000,0.100000,0.320000,500.000000,0.000000,0.000000,0.000000,0.000000,7.000000
25%,2012.000000,0.900000,1.200000,15000.000000,1.000000,0.000000,1.000000,0.000000,9.000000
50%,2014.000000,3.600000,6.400000,32000.000000,1.000000,1.000000,1.000000,0.000000,11.000000
75%,2016.000000,6.000000,9.900000,48767.000000,1.000000,1.000000,1.000000,0.000000,13.000000
max,2018.000000,35.000000,92.600000,500000.000000,2.000000,1.000000,1.000000,3.000000,22.000000

In [22]:
# Target variable
y = df['Selling_Price']

# Features (excluding 'sell ing_price')
x = df.drop(['Selling_Price', "Car_Name"], axis=1)

In [23]:
from sklearn.model_selection import train_test_split

# Split into training and testing (80-20)
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=42)

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# initialize and train model 
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)
#predict
y_pred_lr = lr_model.predict(x_test)

In [25]:
#evaluation

r2 = r2_score(y_test, y_pred_lr)
mae = mean_absolute_error(y_test, y_pred_lr)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_lr))


print("Linear Regression Model Performance:")
print("RÂ² Score:", r2)
print("MAE:", mae)
print("RMSE:", rmse)

Linear Regression Model Performance:
RÂ² Score: 0.8481272601750844
MAE: 1.2205363593717198
RMSE: 1.8704216996615743

In [26]:
# random forest method
from sklearn.ensemble import RandomForestRegressor
# intialize the model
rf_model = RandomForestRegressor(n_estimators=100, random_state = 42)
#train
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [27]:
y_pred_rf = rf_model.predict(x_test)

In [28]:
r2_rf = r2_score(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

print("Random Forest Model Performance:")
print("RÂ² Score:", r2_rf)
print("MAE:", mae_rf)
print("RMSE:", rmse_rf)

Random Forest Model Performance:
RÂ² Score: 0.962046994589421
MAE: 0.6156491803278689
RMSE: 0.9350238841518571

In [29]:
import joblib
joblib.dump(rf_model, 'Car_price_prediction.pkl')

['Car_price_prediction.pkl']

In [36]:
loaded_model = joblib.load("Car_price_prediction.pkl")

In [39]:
sample_data = {
    'Year': [2018, 2014],
    'Present_Price': [6.75, 5.0],
    'Kms_Driven': [25000, 50000],
    'Fuel_Type': [ 1 , 2],
    'Seller_Type': [ 1 , 0],
    'Transmission': [ 1 , 0 ],
    'Owner': [0, 1],
    'Car_Age' : [6 , 11]
}
sample_df = pd.DataFrame(sample_data)
sample_df

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age
0,2018,6.75,25000,1,1,1,0,6
1,2014,5.00,50000,2,0,0,1,11

In [45]:
predicted_price = loaded_model.predict(sample_df)
print("predicted Selling Price 1:" , predicted_price[0])
print("predicted Selling Price 2:" , predicted_price[1])

predicted Selling Price 1: 5.498999999999999
predicted Selling Price 2: 2.8289999999999997